version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "backend_local"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1063f089"
s3_prefix = "backend_local"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[qa]
[qa.deploy]
[qa.deploy.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-og41xft5z3ou"
s3_prefix = "mvp-lite-qa"
region = "ap-south-1"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM","CAPABILITY_AUTO_EXPAND"]
image_repositories = []
